config/routes.rb
Fixapp::Application.routes.draw do

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  get "pages/home"

  get "pages/about"
  
  get "pages/customerRequests"
  
  get "pages/tradespeopleRequests"
  
  get "pages/viewRequests"
  
  
  resources :tradespeople do
	resources :posts
  end
  
  match '/search' => 'tradespeople#search'
  
  match '/tradespeopleRequests' => 'pages#tradespeopleRequests'
  
  match '/about' => 'pages#about'
  
  match '/viewRequests' => 'pages#viewRequests'
  
  match '/signin' => 'sessions#new'
  
  match '/signout' => 'sessions#destroy'   #controller#methodname

  match '/trsignout' => 'sessions#destroytr'
  
  match '/createtr' => 'sessions#createtr'
  
  match '/trsignin' => 'sessions#newtr'
  
  resources :requests

  resources :customers

  resources :tradespeople

  resources :trades
  
  resources :sessions

   root :to => 'pages#home'

end

app/models/customer.rb
class Customer < ActiveRecord::Base
	has_many :requests, :dependent => :destroy
	has_many :posts, :dependent => :destroy
	has_secure_password
	
	validates :name, presence: true
	validates :phone, presence: true
	validates :address, presence: true
	validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/}
	
	geocoded_by :address
	after_validation :geocode, :if => :address_changed?
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  # GET /customers
  # GET /customers.json
  
  
  def index
    @customers = Customer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @customers }
    end
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
    @customer = Customer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @customer }
    end
  end

  # GET /customers/new
  # GET /customers/new.json
  def new
    @customer = Customer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @customer }
    end
  end

  # GET /customers/1/edit
  def edit
    @customer = Customer.find(params[:id])
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(params[:customer])

    respond_to do |format|
      if @customer.save
		Blogmailer.register(@customer).deliver
		#Blogmailer.request(@customer).deliver
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render json: @customer, status: :created, location: @customer }
      else
        format.html { render action: "new" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /customers/1
  # PUT /customers/1.json
  def update
    @customer = Customer.find(params[:id])

    respond_to do |format|
      if @customer.update_attributes(params[:customer])
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to customers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_for(@customer, validate: true) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :photo %><br />
    <%= f.text_field :photo %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>Password must be 8 characters
  </div>
  <div class="field"> 
   <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<h1>Listing customers</h1>

<table cellspacing = 20>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>Phone</th>
    <th>Email</th>
    <th>Photo</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @customers.each do |customer| %>
  <tr>
    <td><%= link_to customer.name, customer  %></td>
    <td><%= customer.address %></td>
    <td><%= customer.phone %></td>
    <td><%= customer.email %></td>
    <td><%= image_tag(customer.photo, :size => '50x50') %></td>
    <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
    <td><%= link_to 'Destroy', customer, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>
<%= link_to 'New Customer', new_customer_path %>
<br />

app/views/customers/new.html.erb
<h1>New customer</h1>

<%= render 'form' %>

<%= link_to 'Make request', new_request_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @customer.name %>
</p>

<p>
  <b>Address:</b>
  <%= @customer.address %>
</p>
<%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@customer.latitude}%2C#{@customer.longitude}" %>

<p>
  <b>Phone:</b>
  <%= @customer.phone %>
</p>

<p>
  <b>Email:</b>
  <%= @customer.email %>
</p>

<p>
  <b>Photo:</b>
  <%= image_tag(@customer.photo, :alt => "My Photo", :size => "100x100") %>
</p>


<%= link_to 'Edit', edit_customer_path(@customer) %> 