config/routes.rb
Fixapp::Application.routes.draw do

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  get "pages/home"

  get "pages/about"
  
  get "pages/customerRequests"
  
  get "pages/tradespeopleRequests"
  
  get "pages/viewRequests"
  
  
  resources :tradespeople do
	resources :posts
  end
  
  match '/search' => 'tradespeople#search'
  
  match '/tradespeopleRequests' => 'pages#tradespeopleRequests'
  
  match '/about' => 'pages#about'
  
  match '/viewRequests' => 'pages#viewRequests'
  
  match '/signin' => 'sessions#new'
  
  match '/signout' => 'sessions#destroy'   #controller#methodname

  match '/trsignout' => 'sessions#destroytr'
  
  match '/createtr' => 'sessions#createtr'
  
  match '/trsignin' => 'sessions#newtr'
  
  resources :requests

  resources :customers

  resources :tradespeople

  resources :trades
  
  resources :sessions

   root :to => 'pages#home'

end

app/models/request.rb
class Request < ActiveRecord::Base
	belongs_to :customer
	belongs_to :tradesperson
	belongs_to :trade
	
	validates :desription, presence: true
	validates :startDate, presence: true
	validates :tradesperson_id, presence: true

	geocoded_by :location
	after_validation :geocode, :if => :location_changed?

end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  # GET /requests
  # GET /requests.json
  
  
  def index
    @requests = Request.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @requests }
    end
  end

  # GET /requests/1
  # GET /requests/1.json
  def show
    @request = Request.find(params[:id])
	@customer = Customer.find(session[:customer_id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @request }
    end
  end

  # GET /requests/new
  # GET /requests/new.json
  def new
    @request = Request.new
	@customer = Customer.find(session[:customer_id])	
	@nearbyTs = Tradesperson.near(@customer.address, 20, :order => :distance, :units => :km)#

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @request }
    end
  end

  
  
  # POST /requests
  # POST /requests.json
  def create
    @request = Request.new(params[:request])
	@request.customer_id = session[:customer_id]
	#@tradesperson = Request.find(params[:tradesperson])
	
    respond_to do |format|
      if @request.save
		#Blogmailer.newRequest(@tradesperson).deliver
        format.html { redirect_to @request, notice: 'Request was successfully created.' }
        format.json { render json: @request, status: :created, location: @request }
      else
        format.html { render action: "new" }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  
  # GET /requests/1/edit
  def edit
    @request = Request.find(params[:id])
  end

  # PUT /requests/1
  # PUT /requests/1.json
  def update
    @request = Request.find(params[:id])

    respond_to do |format|
      if @request.update_attributes(params[:request])
        format.html { redirect_to @request, notice: 'Request was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    @request = Request.find(params[:id])
    @request.destroy

    respond_to do |format|
      format.html { redirect_to requests_url }
      format.json { head :no_content }
    end
  end
  
 
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_form.html.erb
<%= form_for(@request, validate: true) do |f| %>
  <% if @request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
      <% @request.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :desription %>tr
  </div>
  <div class="field">
    <%= f.label :startDate %><br />
    <%= f.text_field :startDate, :id => :datepicker %>
  </div>
  
  <h3> Tradespeople in your area </h3>
  <table border="1">
		<tr>
		<th>Tradesperson Name</th>
		<th>Trade</th>
		<th>Fully qualified</th>
		<th>Location</th>
		</tr>
		<% @nearbyTs.each do |tr| %>
			<tr>
			<td><%= tr.name %></td>
			<td><%= tr.trade.name %></td>
			<td><%= fullyQualified(tr.fullyQualified) %></td>
			<td><%= tr.address %></td>
		<% end %>
		</tr>
		</table>
		
  <h3> Choose Tradesperson </h3>	
  <%= f.collection_select :tradesperson_id, @nearbyTs.all, :id, :name %>
  </br>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/requests/edit.html.erb
<h1>Editing request</h1>

<%= render 'form' %>

<%= link_to 'Show', @request %> |
<%= link_to 'Back', requests_path %>

app/views/requests/index.html.erb
<h1 align="center">Listing requests</h1>
<table cellspacing = 20>
  <tr>
	<th>Customer</th>
    <th>Trade Required</th>
    <th>Desription</th>
    <th>Location</th>
    <th>Startdate</th>
    <th>Tradesperson</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @requests.each do |request| %>
  <tr>
	<td><%= request.customer.name %></td>
    <td><%= request.trade.name %></td>
    <td><%= request.desription %></td>
    <td><%= request.location %></td>
    <td><%= request.startDate %></td>
    <td><%= request.tradesperson.name %></td>
    <td><%= link_to 'Edit', edit_request_path(request) %></td>
	<td><%= link_to 'Destroy', request, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />
<%= link_to 'Make New Request', new_request_path %>

app/views/requests/new.html.erb
<h1>New request</h1>

<%= render 'form' %>

<%= link_to 'Back', requests_path %>

app/views/requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Customer:</b>
  <%= @request.customer.name %>
</p>

<p>
  <b>Customer Location:</b>
  <%= @customer.address %>
</p>


<p>
  <b>Trade Required:</b>
  <%= @request.tradesperson.trade.name %>
</p>

<p>
  <b>Tradesperson Chosen:</b>
  <table border="1">
		<tr>
		<th>Name</th>
		<th>Trade</th>
		<th>Location</th>
		<th>Price/hour</th>
		<th>Phone</th>
		</tr>
		<tr>
		<td><%= @request.tradesperson.name %></td>
		<td><%= @request.tradesperson.trade.name %></td>
		<td><%= @request.tradesperson.address %></td>
		<td><%= @request.tradesperson.trade.price %></td>
		<td><%= @request.tradesperson.phone %></td>
		</tr>
		</table>
</p>

<p>
  <b>Job Desription:</b>
  <%= @request.desription %>
</p>

<p>
  <b>Startdate:</b>
  <%= @request.startDate %>
</p>

<p>
	<h2> <%= @request.tradesperson.name %> will contact you in the next few minutes</h2>
</p>

<%= link_to 'Edit', edit_request_path(@request) %> |