config/routes.rb
Fixapp::Application.routes.draw do

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  get "pages/home"

  get "pages/about"
  
  get "pages/customerRequests"
  
  get "pages/tradespeopleRequests"
  
  get "pages/viewRequests"
  
  
  resources :tradespeople do
	resources :posts
  end
  
  match '/search' => 'tradespeople#search'
  
  match '/tradespeopleRequests' => 'pages#tradespeopleRequests'
  
  match '/about' => 'pages#about'
  
  match '/viewRequests' => 'pages#viewRequests'
  
  match '/signin' => 'sessions#new'
  
  match '/signout' => 'sessions#destroy'   #controller#methodname

  match '/trsignout' => 'sessions#destroytr'
  
  match '/createtr' => 'sessions#createtr'
  
  match '/trsignin' => 'sessions#newtr'
  
  resources :requests

  resources :customers

  resources :tradespeople

  resources :trades
  
  resources :sessions

   root :to => 'pages#home'

end

app/models/trade.rb
class Trade < ActiveRecord::Base
	has_many :requests
	
end

app/controllers/trades_controller.rb
class TradesController < ApplicationController
  # GET /trades
  # GET /trades.json
  
  before_filter :authorise, :only => [:edit, :delete, :new]
  
  def index
    @trades = Trade.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @trades }
    end
  end

  # GET /trades/1
  # GET /trades/1.json
  def show
    @trade = Trade.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @trade }
    end
  end

  # GET /trades/new
  # GET /trades/new.json
  def new
    @trade = Trade.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @trade }
    end
  end

  # GET /trades/1/edit
  def edit
    @trade = Trade.find(params[:id])
  end

  # POST /trades
  # POST /trades.json
  def create
    @trade = Trade.new(params[:trade])

    respond_to do |format|
      if @trade.save
        format.html { redirect_to @trade, notice: 'Trade was successfully created.' }
        format.json { render json: @trade, status: :created, location: @trade }
      else
        format.html { render action: "new" }
        format.json { render json: @trade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /trades/1
  # PUT /trades/1.json
  def update
    @trade = Trade.find(params[:id])

    respond_to do |format|
      if @trade.update_attributes(params[:trade])
        format.html { redirect_to @trade, notice: 'Trade was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @trade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trades/1
  # DELETE /trades/1.json
  def destroy
    @trade = Trade.find(params[:id])
    @trade.destroy

    respond_to do |format|
      format.html { redirect_to trades_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/trades_helper.rb
module TradesHelper
end

app/views/trades/_form.html.erb
<%= form_for(@trade) do |f| %>
  <% if @trade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trade.errors.count, "error") %> prohibited this trade from being saved:</h2>

      <ul>
      <% @trade.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trades/edit.html.erb
<h1>Editing trade</h1>

<%= render 'form' %>

<%= link_to 'Show', @trade %> |
<%= link_to 'Back', trades_path %>

app/views/trades/index.html.erb
<h1 align="center">Listing trades</h1>
<table cellspacing = 20 align="center">
  <tr>
    <th>Name</th>
    <th>Price/hour</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @trades.each do |trade| %>
  <tr>
    <td><%= trade.name %></td>
    <td><%= euro(trade.price) %></td>
    <td><%= link_to 'Edit', edit_trade_path(trade) %></td>
	<td><%= link_to 'Destroy', trade, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />
<% if trsigned_in? %>
<%= link_to 'New Trade', new_trade_path %>
<% end %>

app/views/trades/new.html.erb
<h1>New trade</h1>

<%= render 'form' %>

<%= link_to 'Back', trades_path %>

app/views/trades/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @trade.name %>
</p>

<p>
  <b>Price/hour:</b>
  <%= @trade.price %>
</p>


<%= link_to 'Edit', edit_trade_path(@trade) %> |
<%= link_to 'Back', trades_path %>