config/routes.rb
Fixapp::Application.routes.draw do

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  get "pages/home"

  get "pages/about"
  
  get "pages/customerRequests"
  
  get "pages/tradespeopleRequests"
  
  get "pages/viewRequests"
  
  
  resources :tradespeople do
	resources :posts
  end
  
  match '/search' => 'tradespeople#search'
  
  match '/tradespeopleRequests' => 'pages#tradespeopleRequests'
  
  match '/about' => 'pages#about'
  
  match '/viewRequests' => 'pages#viewRequests'
  
  match '/signin' => 'sessions#new'
  
  match '/signout' => 'sessions#destroy'   #controller#methodname

  match '/trsignout' => 'sessions#destroytr'
  
  match '/createtr' => 'sessions#createtr'
  
  match '/trsignin' => 'sessions#newtr'
  
  resources :requests

  resources :customers

  resources :tradespeople

  resources :trades
  
  resources :sessions

   root :to => 'pages#home'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fixapp</title>
  <%= stylesheet_link_tag  "http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/redmond/jquery-ui.css",  "application", :media => "all" %>
  <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js", "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/jquery-ui.min.js", "application" %>
  <%= csrf_meta_tags %>
</head>

<body>

<div id="banner">
	<%= image_tag("cursor.jpg", :size => "100x50") %>
	<%= @page_title || "Fix with a Click" %>
	<%="paul benson"%>
</div>

<div id="nav" align="center">
	<ul>
	<% if !trsigned_in? and !signed_in?%>
		<li><%= link_to "Customer Sign In", signin_path %></li>
		<li><%= link_to "Trades Person Sign In", trsignin_path %></li>
		<li><%= link_to "Trades Available", trades_path %></li>
		<li><%= link_to "Home", root_path%></li>
		<li><%= link_to "About", about_path%></li>
	<%end%>	
	<% if trsigned_in?%>
		<li>Signed in as <%= @current_tr.name %></li>
		<li><%= link_to "Sign Out", trsignout_path%></li>
		<li><%= link_to "My Profile", @current_tr%></li>
		<li><%= link_to "View Requests", tradespeopleRequests_path%></li>
		<li><%= link_to "Home", root_path %></li>
	<%end%>
	<% if signed_in?%>
		<li>Signed in as <%= @current_customer.name %></li>
		<li><%= link_to "Sign Out", signout_path%></li>
		<li><%= link_to "My Profile", @current_customer%></li>
		<li><%= link_to "Make New Request", new_request_path%></li>
		<li><%= link_to "View Requests", viewRequests_path%></li>
		<li><%= link_to "View Tradespeople", tradespeople_path%></li>
		<li><%= link_to "Home", root_path %></li>
	<%end%>
    </ul>
</div>


<%= yield %>
<p style="color: red"><%= flash[:error] %></p>
</body>
</html>